# Makefile for Arduino Uno
#
# show details for valiables in
# https://github.com/sudar/Arduino-Makefile/blob/master/arduino-mk-vars.md#compilerexecutable-variables
#
# library dependence
# * Arduino IDE v1.6.7

BOARD_TAG = uno
ARDUINO_DIR = /Applications/Arduino.app/Contents/Java
MONITOR_PORT = /dev/cu.usb*

include $(ARDMK_DIR)/Arduino.mk
