PROJECT_DIR = /Users/uehashu/Codes/Arduino/HHKBLite2BT/sketch/promicro8
ARDMK_DIR = /usr/local/Cellar/arduino-mk/1.5
AVR_TOOLS_DIR = /usr/local
BOARD_TAG = promicro8
#MCU = atmega32u4
#F_CPU = 16000000
AVRDUDE = /usr/local/bin/avrdude
MONITOR_PORT = /dev/cu.usb*

ARDUINO_SPARKFUN = $(ARDUINO_DIR)/hardware/sparkfun
ARDUINO_PLATFORM_LIB_PATH = $(ARDUINO_SPARKFUN)/avr/libraries
ARDUINO_VAR_PATH = $(ARDUINO_SPARKFUN)/avr/variants
BOARDS_TXT = $(ARDUINO_SPARKFUN)/avr/boards.txt
#ARDUINO_LIB_PATH = $(ARDUINO_LIB_PATH):$(ARDUINO_DIR)/hardware/arduino/avr/libraries
#ARDUINO_LIB_PATH = $(ARDUINO_DIR)/hardware/arduino/avr/libraries
ARDUINO_CORE_PATH = $(ARDUINO_SPARKFUN)/avr/cores/arduino
BOOTLOADER_PARENT = $(ARDUINO_SPARKFUN)/avr/bootloaders
ARDUINO_HEADER = $(ARDUINO_DIR)/hardware/arduino/avr/cores/arduino/Arduino.h

include $(ARDMK_DIR)/Arduino.mk
